// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionTypeEnum =
  | 'CREATE'
  | 'READ'
  | 'UPDATE'
  | 'DELETE'
  | 'MANAGE'
  | 'PUBLISH'
  | 'MODERATE'
  | 'GRADE'
  | 'TAKE'
  | 'VIEW_RESULTS'
  | 'VIEW_ANY_RESULTS'
  | 'ASSIGN_ROLES'
  | 'VIEW_ANALYTICS'
  | 'MANAGE_SETTINGS'
  | 'AUDIT'
