// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type ActionTypeEnum =
  | "CREATE"
  | "READ"
  | "UPDATE"
  | "DELETE"
  | "MANAGE"
  | "PUBLISH"
  | "MODERATE"
  | "GRADE"
  | "TAKE"
  | "VIEW_RESULTS"
  | "VIEW_ANY_RESULTS"
  | "ASSIGN_ROLES"
  | "VIEW_ANALYTICS"
  | "MANAGE_SETTINGS"
  | "AUDIT";
