// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type AttemptResultResponse = {
  attempt_id: string;
  total_questions: number;
  correct_answers: number;
  score_percent: number;
  passed: boolean;
};
