// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AttentionQueryParams = {
  sort_by?: string;
  sort_order?: string;
  search?: string;
  issue?: string;
  page?: number;
  limit?: number;
};
