// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthPermissionResponse } from "./AuthPermissionResponse";
import type { AuthRoleResponse } from "./AuthRoleResponse";
import type { AuthUserResponse } from "./AuthUserResponse";

export type AuthResponse = {
  user: AuthUserResponse;
  roles: Array<AuthRoleResponse>;
  permissions: Array<AuthPermissionResponse>;
};
