// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { AuthPermissionResponse } from "@/generated-types/AuthPermissionResponse";
import type { AuthRoleResponse } from "@/generated-types/AuthRoleResponse";
import type { AuthUserResponse } from "@/generated-types/AuthUserResponse";

export type AuthResponse = {
  user: AuthUserResponse;
  roles: Array<AuthRoleResponse>;
  permissions: Array<AuthPermissionResponse>;
};
