// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type ChapterItem = {
  id: string;
  name: string;
  published_topics: bigint;
  total_topics: bigint;
  coverage: number;
  avg_recall: string;
  practice_accuracy: number;
  status: string;
  last_updated: string;
};
