// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChaptersQueryParams = {
  search?: string;
  sort_by?: string;
  sort_order?: string;
  page?: bigint;
  limit?: bigint;
};
