// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type ChapterSummary = {
  subject_name: string;
  total_chapters: bigint;
  published_topics: bigint;
  draft_topics: bigint;
  chapters_needing_attention: bigint;
};
