// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChapterDto = {
  id: string;
  name: string;
  subject_id: string;
  order_number: number;
};
