// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { ChapterDto } from "@/generated-types/ChapterDto";
import type { PaginationInfo } from "@/generated-types/PaginationInfo";

export type ChaptersResponse = {
  chapters: Array<ChapterDto>;
  pagination: PaginationInfo | null;
};
