// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChapterSummary = {
  subject_name: string;
  total_chapters: bigint;
  published_topics: bigint;
  draft_topics: bigint;
  chapters_needing_attention: bigint;
};
