// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommunityPostResponse = {
  id: string;
  thread_id: string;
  user_id: string;
  content: string;
};
