// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDashboardAttentionItem } from "./ContentDashboardAttentionItem";

export type ContentDashboardAttentionResponse = {
  total: bigint;
  items: Array<ContentDashboardAttentionItem>;
};
