// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentDashboardSummary = {
  subjects_covered: bigint;
  topics_published: bigint;
  topics_in_draft: bigint;
  topics_flagged: bigint;
};
