// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentDashboardAttentionItem = {
  id: string;
  topic: string;
  issue: string;
  reason: string;
  students_affected: bigint;
};
