// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type ContentDashboardAttentionItem = {
  id: string;
  topic: string;
  issue: string;
  reason: string;
  students_affected: bigint;
};
