// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { ContentDashboardAttentionItem } from "@/generated-types/ContentDashboardAttentionItem";

export type ContentDashboardAttentionResponse = {
  total: bigint;
  items: Array<ContentDashboardAttentionItem>;
};
