// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type ContentDashboardSummary = {
  subjects_covered: bigint;
  topics_published: bigint;
  topics_in_draft: bigint;
  topics_flagged: bigint;
};
