// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type ContentDashboardSubjectProgress = {
  id: string;
  name: string;
  completion: number;
  total_topics: bigint;
  published_topics: bigint;
  draft_topics: bigint;
};
