// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentDashboardSignalItem } from "./ContentDashboardSignalItem";

export type ContentDashboardSignalsResponse = {
  highest_recall: Array<ContentDashboardSignalItem>;
  fastest_decay: Array<ContentDashboardSignalItem>;
};
