// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { ContentDashboardSignalItem } from "@/generated-types/ContentDashboardSignalItem";

export type ContentDashboardSignalsResponse = {
  highest_recall: Array<ContentDashboardSignalItem>;
  fastest_decay: Array<ContentDashboardSignalItem>;
};
