// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTestRequest = {
  title: string;
  description?: string;
  instructions?: string;
  duration_minutes?: number;
  passing_score?: number;
  max_attempts?: number;
  visibility?: string;
  status?: string;
  question_ids: Array<string>;
};
