// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateReferencePayload = {
  title: string;
  source: string;
  reference_type: string;
  url: string;
};
