// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateQuestionRequest = {
  question: string;
  question_type: string;
  difficulty: string;
  correct_answer: string;
  explanation?: string;
  common_mistakes?: string;
  hints?: string;
  learning_objective?: string;
  estimated_time?: number;
  status?: string;
  tags?: Array<string>;
  choices?: Array<string>;
  tolerance?: string;
  unit?: string;
  rubric?: string;
  evaluation_criteria?: string;
  assertion_reason_assertion?: string;
  assertion_reason_reason?: string;
};
