// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateNoteRequest = {
  topic_id: string;
  title: string;
  content: string;
};
