// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { CriticalIssue } from "@/generated-types/CriticalIssue";

export type CriticalIssuesResponse = {
  total_urgent: bigint;
  issues: Array<CriticalIssue>;
};
