// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CriticalIssue } from "./CriticalIssue";

export type CriticalIssuesResponse = {
  total_urgent: bigint;
  issues: Array<CriticalIssue>;
};
