// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { IssueSeverity } from "@/generated-types/IssueSeverity";

export type CriticalIssue = {
  id: string;
  topic: string;
  description: string;
  severity: IssueSeverity;
  students_affected: bigint;
  action_label: string;
};
