// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Modified by generate-types to replace union type with const object (Biome-compatible). DO NOT EDIT.

export const ErrorCode = {
  "VALIDATION": "VALIDATION",
  "AUTH": "AUTH",
  "ACCESS_TOKEN_EXPIRED": "ACCESS_TOKEN_EXPIRED",
  "REFRESH_TOKEN_EXPIRED": "REFRESH_TOKEN_EXPIRED",
  "UNAUTHORIZED": "UNAUTHORIZED",
  "NOT_FOUND": "NOT_FOUND",
  "CONFLICT": "CONFLICT",
  "INTERNAL": "INTERNAL",
} as const;

export type TErrorCode = typeof ErrorCode[keyof typeof ErrorCode];
