// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissingConceptItem } from "@/generated-types/MissingConceptItem";

export type FreeRecallResponse = {
  participation_rate: number;
  ai_clarity_score: number;
  average_response_length: bigint;
  missing_concepts: Array<MissingConceptItem>;
};
