// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { InsightsSortBy } from "@/generated-types/InsightsSortBy";
import type { SortOrder } from "@/generated-types/SortOrder";

export type InsightSort = { sort_by?: InsightsSortBy; sort_order?: SortOrder };
