// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type InsightType =
  | "quiz_review_pending"
  | "low_attendance"
  | "topic_difficulty"
  | "low_engagement"
  | "system_alert";
