// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InsightType =
  | "quiz_review_pending"
  | "low_attendance"
  | "topic_difficulty"
  | "low_engagement"
  | "system_alert";
