// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { InsightSeverity } from "@/generated-types/InsightSeverity";
import type { InsightType } from "@/generated-types/InsightType";
import type { JsonValue } from "@/generated-types/serde_json/JsonValue";

export type Insight = {
  id: string;
  insight_type: InsightType;
  severity: InsightSeverity;
  title: string;
  description: string;
  metadata: JsonValue;
  detected_at: Date;
};
