// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { InsightSeverity } from "@/generated-types/InsightSeverity";
import type { InsightType } from "@/generated-types/InsightType";

export type InsightFilters = {
  severity?: InsightSeverity;
  insight_type?: InsightType;
  start?: bigint;
  end?: bigint;
};
