// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InsightSeverity } from "./InsightSeverity";
import type { InsightType } from "./InsightType";
import type { InsightsSortBy } from "./InsightsSortBy";
import type { SortOrder } from "./SortOrder";

export type InsightsQueryParams = {
  page?: number;
  limit?: number;
  search?: string;
  severity?: InsightSeverity;
  insight_type?: InsightType;
  start?: bigint;
  end?: bigint;
  sort_by?: InsightsSortBy;
  sort_order?: SortOrder;
};
