// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Insight } from "./Insight";
import type { InsightSummary } from "./InsightSummary";
import type { PaginationResponse } from "./PaginationResponse";
import type { TimeWindow } from "./TimeWindow";

export type InsightsResponse = {
  time_window: TimeWindow;
  insights: Array<Insight>;
  summary: InsightSummary;
  pagination: PaginationResponse;
};
