// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type LiveClassResponse = {
  id: string;
  topic_id: string;
  scheduled_at: Date;
  duration_min: number;
  provider: string;
  join_url: string;
};
