// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { LiveClassResponse } from "@/generated-types/LiveClassResponse";
import type { PaginationResponse } from "@/generated-types/PaginationResponse";

export type LiveClassesResponse = {
  classes: Array<LiveClassResponse>;
  pagination: PaginationResponse;
};
