// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type LiveSessionResponse = {
  id: string;
  title: string;
  scheduled_at: string;
  instructor: string;
};
