// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McqQuestionItem = {
  question_number: string;
  concept: string;
  difficulty: string;
  recall_accuracy: number;
  attempts: bigint;
};
