// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DifficultyBreakdownItem } from "@/generated-types/DifficultyBreakdownItem";
import type { McqQuestionItem } from "@/generated-types/McqQuestionItem";

export type McqRecallResponse = {
  overall_accuracy: number;
  total_questions_attempted: bigint;
  difficulty_breakdown: Array<DifficultyBreakdownItem>;
  questions: Array<McqQuestionItem>;
};
