// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryGapItem } from "@/generated-types/MemoryGapItem";

export type MemoryGapMapResponse = { items: Array<MemoryGapItem> };
