// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecallStatus } from "@/generated-types/RecallStatus";

export type MemoryGapItem = {
  concept: string;
  recall_status: RecallStatus;
  confidence: number;
  correctness: number;
  mismatch_alert?: string;
};
