// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionResponse } from './PermissionResponse'
import type { RoleResponse } from './RoleResponse'
import type { UserResponse } from './UserResponse'

export type MeResponse = {
  user: UserResponse
  roles: Array<RoleResponse>
  permissions: Array<PermissionResponse>
}
