// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MissingConceptItem = {
  concept: string;
  percentage_missing: number;
  ai_summary: string;
};
