// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotesOverview = {
  teacher_notes_status: string;
  ai_notes_status: string;
  external_references_count: number;
  student_engagement: number;
};
