// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type NoteResponse = {
  id: string;
  user_id: string;
  topic_id: string;
  title: string;
  content: string;
  is_official: boolean;
};
