// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type NotificationResponse = {
  id: string;
  user_id: string;
  title: string;
  message: string;
  status: string;
};
