// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { NotificationResponse } from "@/generated-types/NotificationResponse";

export type NotificationListResponse = {
  notifications: Array<NotificationResponse>;
  total_count: number;
};
