// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type PaginationResponse = {
  page: number;
  limit: number;
  total: bigint;
  filtered_total: bigint;
  total_pages: number;
};
