// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { RecallStrength } from "@/generated-types/RecallStrength";
import type { StatusTrend } from "@/generated-types/StatusTrend";

export type PainPointItem = {
  id: string;
  topic: string;
  recall_strength: RecallStrength;
  accuracy: number;
  common_mistake: string;
  last_activity: string;
  status: StatusTrend;
  students: bigint;
};
