// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { PainPointSortBy } from "@/generated-types/PainPointSortBy";
import type { SortOrder } from "@/generated-types/SortOrder";

export type PainPointSort = {
  sort_by?: PainPointSortBy;
  sort_order?: SortOrder;
};
