// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PainPointItem } from "./PainPointItem";

export type PainPointsResponse = { total: bigint; items: Array<PainPointItem> };
