// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { ResourcePermissionResponse } from "@/generated-types/ResourcePermissionResponse";

export type PermissionSummaryResponse = {
  user_id: string;
  has_permission: boolean;
  permissions: Array<string>;
  resource_permissions: Array<ResourcePermissionResponse>;
};
