// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { ActionTypeEnum } from "@/generated-types/ActionTypeEnum";
import type { ResourceTypeEnum } from "@/generated-types/ResourceTypeEnum";

export type PermissionResponse = {
  id: string;
  name: string;
  resource_type: ResourceTypeEnum;
  action: ActionTypeEnum;
  description: string | null;
  created_at: Date;
  updated_at: Date;
};
