// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PermissionResponse = {
  id: string;
  name: string;
  resource_type: string;
  action: string;
  description: string | null;
};
