// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourcePermissionResponse } from "./ResourcePermissionResponse";

export type PermissionSummaryResponse = {
  user_id: string;
  has_permission: boolean;
  permissions: Array<string>;
  resource_permissions: Array<ResourcePermissionResponse>;
};
