// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionTypeEnum } from './ActionTypeEnum'
import type { ResourceTypeEnum } from './ResourceTypeEnum'

export type PermissionResponse = {
  id: string
  name: string
  resource_type: ResourceTypeEnum
  action: ActionTypeEnum
  description: string | null
  created_at: Date
  updated_at: Date
}
