// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type PlaybackTokenResponse = {
  playback_token: string;
  expires_at: Date;
};
