// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignalType } from "./SignalType";

export type PracticeSignal = {
  id: string;
  message: string;
  signal_type: SignalType;
};
