// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PracticeOverview = {
  total_questions: bigint;
  average_accuracy: number;
  total_tests: bigint;
  last_test_conducted: string;
};
