// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type ProgressResponse = {
  id: string;
  user_id: string;
  topic_id: string;
  progress_percent: number;
};
