// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuestionPerformanceItem = {
  question_id: string;
  question: string;
  correct_rate: number;
  attempts: bigint;
};
