// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuestionsQueryParams = {
  search?: string;
  question_type?: string;
  difficulty?: string;
  status?: string;
  sort_by?: string;
  sort_order?: string;
  page?: bigint;
  limit?: bigint;
};
