// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type QuestionResponse = {
  id: string;
  quiz_id: string;
  question_text: string;
  question_type: string;
};
