// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionItem } from "./QuestionItem";

export type QuestionsResponse = {
  items: Array<QuestionItem>;
  total: bigint;
  page: bigint;
  limit: bigint;
  total_pages: bigint;
};
