// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuestionItem = {
  id: string;
  identifier: string;
  question: string;
  question_type: string;
  difficulty: string;
  correct_rate?: number;
  status: string;
};
