// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type QuizResponse = {
  id: string;
  title: string;
  description: string;
  time_limit_minutes: number;
  passing_score: number;
};
