// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuizResponse = {
  id: string;
  title: string;
  description: string;
  time_limit_minutes: number;
  passing_score: number;
};
