// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecallOverview = {
  avg_recall_score: number;
  completion_rate: number;
  memory_decay: string;
  last_recall_run: string;
};
