// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecallQuestionResponse = {
  id: string;
  question: string;
  options: Array<string>;
  correct_answer: number;
};
