// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecallTrendDataPoint } from "@/generated-types/RecallTrendDataPoint";

export type RecallTrendsResponse = {
  recall_trend: Array<RecallTrendDataPoint>;
  memory_decay_curve: Array<RecallTrendDataPoint>;
  recall_by_difficulty: Array<RecallTrendDataPoint>;
  retention_distribution: Array<RecallTrendDataPoint>;
};
