// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordingResponse = {
  id: string;
  session_id: string;
  recording_url: string;
};
