// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { UserTypeEnums } from "@/generated-types/UserTypeEnums";

export type RegisterUserRequest = {
  email: string;
  password: string;
  user_type: UserTypeEnums;
};
