// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserTypeEnums } from './UserTypeEnums'

export type RegisterUserRequest = {
  email: string
  password: string
  user_type: UserTypeEnums
}
