// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { ActionTypeEnum } from "@/generated-types/ActionTypeEnum";
import type { OwnershipType } from "@/generated-types/OwnershipType";
import type { ResourceTypeEnum } from "@/generated-types/ResourceTypeEnum";

export type ResourcePermissionResponse = {
  resource_type: ResourceTypeEnum;
  action: ActionTypeEnum;
  ownership: OwnershipType;
  resource_id: string | null;
};
