// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoleResponse = {
  id: string;
  name: string;
  display_name: string;
  description: string | null;
  is_system_role: boolean;
};
