// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { UserTypeEnums } from "@/generated-types/UserTypeEnums";

export type RoleResponse = {
  id: string;
  name: UserTypeEnums;
  display_name: string;
  description: string | null;
  is_system_role: boolean;
  created_at: Date;
  updated_at: Date;
};
