// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserTypeEnums } from './UserTypeEnums'

export type RoleResponse = {
  id: string
  name: UserTypeEnums
  display_name: string
  description: string | null
  is_system_role: boolean
  created_at: Date
  updated_at: Date
}
