// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type SubjectSummary = {
  total_subjects: bigint;
  total_topics: bigint;
  published_topics: bigint;
  topics_needing_attention: bigint;
  descriptions: Array<string>;
};
