// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubjectSummary = {
  total_subjects: bigint;
  total_topics: bigint;
  published_topics: bigint;
  topics_needing_attention: bigint;
  descriptions: Array<string>;
};
