// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type SubjectPageItem = {
  id: string;
  name: string;
  chapters_count: bigint;
  topics_published: bigint;
  coverage: number;
  average_recall?: number;
  practice_accuracy?: number;
  status: string;
};
