// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubjectSignalType } from "./SubjectSignalType";

export type SubjectSignal = {
  subject_name: string;
  message: string;
  signal_type: SubjectSignalType;
};
