// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { SubjectSignalType } from "@/generated-types/SubjectSignalType";

export type SubjectSignal = {
  subject_name: string;
  message: string;
  signal_type: SubjectSignalType;
};
