// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type SubjectDto = {
  id: string;
  name: string;
  description: string | null;
  icon_url: string | null;
};
