// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { SubmitAnswerPayload } from "@/generated-types/SubmitAnswerPayload";

export type SubmitAttemptRequest = { answers: Array<SubmitAnswerPayload> };
