// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SuggestedActionItem = {
  id: string;
  icon: string;
  detected_issue: string;
  explanation: string;
  suggested_fix: string;
  primary_cta: string;
};
