// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DifficultyDistributionItem } from "./DifficultyDistributionItem";
import type { QuestionPerformanceItem } from "./QuestionPerformanceItem";
import type { TrendDataPoint } from "./TrendDataPoint";

export type TestAnalytics = {
  average_score_trend: Array<TrendDataPoint>;
  attempts_trend: Array<TrendDataPoint>;
  difficulty_distribution: Array<DifficultyDistributionItem>;
  question_performance: Array<QuestionPerformanceItem>;
};
