// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type TokenResponse = {
  access_token: string;
  refresh_token: string;
  token_type: string;
  expires_in: bigint;
};
