// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TopicsQueryParams = {
  search?: string;
  sort_by?: string;
  sort_order?: string;
  status_filter?: string;
  content_status_filter?: string;
  recall_filter?: string;
  video_filter?: string;
  page?: bigint;
  limit?: bigint;
};
