// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrendDataPoint } from "./TrendDataPoint";

export type TopicTrends = {
  recall_trend: Array<TrendDataPoint>;
  practice_accuracy_trend: Array<TrendDataPoint>;
  engagement_trend: Array<TrendDataPoint>;
  completion_trend: Array<TrendDataPoint>;
};
