// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type TopicItem = {
  id: string;
  name: string;
  content_status: string;
  video_available: boolean;
  recall_strength: string;
  practice_accuracy: number;
  last_activity: string;
  status: string;
};
