// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TopicDto = {
  id: string;
  name: string;
  chapter_id: string;
  order_number: number;
  subject_id: string;
  chapter_name: string;
  subject_name: string;
};
