// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type TopicDifficultyMetadata = {
  topic_id: string;
  avg_progress: number;
  attempt_count: bigint;
};
