// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type TopicPerformanceSortBy =
  | "topic_name"
  | "recall_strength_mcq"
  | "recall_strength_reflection"
  | "practice_accuracy"
  | "students_affected";
