// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TopicTestItem = {
  id: string;
  title: string;
  status: string;
  questions_count: bigint;
  difficulty_mix: string;
  average_score?: number;
  attempts: bigint;
};
