// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TopicOverview = {
  recall_strength: string;
  practice_accuracy: number;
  dropoff_indicator: string;
  engagement_trend: string;
};
