// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TopicSummary = {
  chapter_name: string;
  total_topics: bigint;
  published_topics: bigint;
  draft_topics: bigint;
  weak_topics: bigint;
};
