// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { PaginationInfo } from "@/generated-types/PaginationInfo";
import type { TopicDto } from "@/generated-types/TopicDto";

export type TopicsResponse = {
  topics: Array<TopicDto>;
  pagination: PaginationInfo | null;
};
