// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationResponse } from "./PaginationResponse";
import type { TopicPerformance } from "./TopicPerformance";

export type TopicPerformanceResponse = {
  topics: Array<TopicPerformance>;
  pagination: PaginationResponse;
};
