// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type TopicPerformance = {
  topic_id: string;
  subject_id: string;
  topic_name: string;
  chapter_name: string;
  subject_name: string;
  recall_strength_mcq?: number;
  recall_strength_reflection?: number;
  practice_accuracy: number;
  students_affected: bigint;
  total_students: bigint;
};
