// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TopicDetailResponse = {
  topic: string;
  accuracy: number;
  students_affected: bigint;
  trend: string;
  common_mistakes: Array<string>;
  weak_questions: Array<string>;
  recommendations: Array<string>;
};
