// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type TopicDetailResponse = {
  topic: string;
  accuracy: number;
  students_affected: bigint;
  trend: string;
  common_mistakes: Array<string>;
  weak_questions: Array<string>;
  recommendations: Array<string>;
};
