// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TopicIssue = {
  id: string;
  title: string;
  severity: string;
  description: string;
  recommendation: string;
  action_label: string;
};
