// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TopicAction = {
  id: string;
  label: string;
  description?: string;
  icon?: string;
};
