// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TopicDifficultyMetadata = {
  topic_id: string;
  avg_progress: number;
  attempt_count: bigint;
};
