// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type UserResponse = {
  id: string;
  email: string;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
};
