// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { PermissionResponse } from "@/generated-types/PermissionResponse";
import type { ResourcePermissionResponse } from "@/generated-types/ResourcePermissionResponse";
import type { RoleResponse } from "@/generated-types/RoleResponse";
import type { UserResponse } from "@/generated-types/UserResponse";

export type UserProfileResponse = {
  user: UserResponse;
  roles: Array<RoleResponse>;
  permissions: Array<PermissionResponse>;
  resource_permissions: Array<ResourcePermissionResponse>;
};
