// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type UserProfileDataResponse = {
  first_name: string | null;
  last_name: string | null;
  avatar_url: string | null;
};
