// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserResponse = {
  id: string
  email: string
  is_active: boolean
  created_at: Date
  updated_at: Date
}
