// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { PermissionResponse } from "@/generated-types/PermissionResponse";
import type { ResourcePermissionResponse } from "@/generated-types/ResourcePermissionResponse";

export type UserPermissionResponse = {
  rbac_permissions: Array<PermissionResponse>;
  acl_permissions: Array<ResourcePermissionResponse>;
};
