// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoDto = {
  id: string;
  topic_id: string;
  title: string;
  duration_seconds: number;
  video_url: string;
  transcript: string | null;
};
