// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.

export type VideoDto = {
  id: string;
  topic_id: string;
  title: string;
  duration_seconds: number;
  video_url: string;
  transcript: string | null;
};
