// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// Relative imports converted to absolute imports by generate-types recipe. DO NOT EDIT.
import type { PaginationResponse } from "@/generated-types/PaginationResponse";
import type { VideoDto } from "@/generated-types/VideoDto";

export type VideosResponse = {
  videos: Array<VideoDto>;
  pagination: PaginationResponse | null;
};
