// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IssueSeverity } from "./IssueSeverity";

export type CriticalIssue = {
  id: string;
  topic: string;
  description: string;
  severity: IssueSeverity;
  students_affected: bigint;
  action_label: string;
};
