// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export enum ErrorCode {
  "VALIDATION",
  "AUTH",
  "ACCESS_TOKEN_EXPIRED",
  "REFRESH_TOKEN_EXPIRED",
  "UNAUTHORIZED",
  "NOT_FOUND",
  "CONFLICT",
  "INTERNAL",
}
