// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InsightSummary = {
  total: number;
  filtered_item: string | null;
  filtered_item_count: number;
  danger: number;
  success: number;
  neutral: number;
  warning: number;
  info: number;
};
