// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InsightsSortBy } from "./InsightsSortBy";
import type { SortOrder } from "./SortOrder";

export type InsightSort = { sort_by?: InsightsSortBy; sort_order?: SortOrder };
