// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InsightSeverity } from "./InsightSeverity";
import type { InsightType } from "./InsightType";
import type { JsonValue } from "./serde_json/JsonValue";

export type Insight = {
  id: string;
  insight_type: InsightType;
  severity: InsightSeverity;
  title: string;
  description: string;
  metadata: JsonValue;
  detected_at: Date;
};
