// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LowAttendanceMetadata = {
  session_id: string;
  topic_id: string;
  attendee_count: bigint;
};
