// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationResponse } from "./NotificationResponse";

export type NotificationListResponse = {
  notifications: Array<NotificationResponse>;
  total_count: number;
};
