// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaginationResponse = {
  page: number;
  limit: number;
  total: bigint;
  filtered_total: bigint;
  total_pages: number;
};
