// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PainPointSortBy } from "./PainPointSortBy";
import type { SortOrder } from "./SortOrder";

export type PainPointSort = {
  sort_by?: PainPointSortBy;
  sort_order?: SortOrder;
};
