// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecallStrength } from "./RecallStrength";
import type { StatusTrend } from "./StatusTrend";

export type PainPointItem = {
  id: string;
  topic: string;
  recall_strength: RecallStrength;
  accuracy: number;
  common_mistake: string;
  last_activity: string;
  status: StatusTrend;
  students: bigint;
};
