// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProgressResponse = {
  id: string;
  user_id: string;
  topic_id: string;
  progress_percent: number;
};
