// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuestionResponse = {
  id: string;
  quiz_id: string;
  question_text: string;
  question_type: string;
};
