// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionTypeEnum } from "./ActionTypeEnum";
import type { OwnershipType } from "./OwnershipType";
import type { ResourceTypeEnum } from "./ResourceTypeEnum";

export type ResourcePermissionResponse = {
  resource_type: ResourceTypeEnum;
  action: ActionTypeEnum;
  ownership: OwnershipType;
  resource_id: string | null;
};
