// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubjectDto = {
  id: string;
  name: string;
  description: string | null;
  icon_url: string | null;
};
