// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortOrder } from "./SortOrder";
import type { TopicPerformanceSortBy } from "./TopicPerformanceSortBy";

export type TopicPerformanceQueryParams = {
  subject_id?: string;
  chapter_id?: string;
  topic_id?: string;
  page?: number;
  limit?: number;
  search?: string;
  sort_by?: TopicPerformanceSortBy;
  sort_order?: SortOrder;
};
