// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TopicPerformanceSortBy =
  | "topic_name"
  | "recall_strength_mcq"
  | "recall_strength_reflection"
  | "practice_accuracy"
  | "students_affected";
