// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortOrder } from "./SortOrder";
import type { TopicPerformanceSortBy } from "./TopicPerformanceSortBy";

export type TopicPerformanceSort = {
  sort_by?: TopicPerformanceSortBy;
  sort_order?: SortOrder;
};
