// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionResponse } from "./PermissionResponse";
import type { ResourcePermissionResponse } from "./ResourcePermissionResponse";
import type { RoleResponse } from "./RoleResponse";
import type { UserProfileDataResponse } from "./UserProfileDataResponse";
import type { UserResponse } from "./UserResponse";

export type UserProfileResponse = {
  user: UserResponse;
  profile: UserProfileDataResponse;
  roles: Array<RoleResponse>;
  permissions: Array<PermissionResponse>;
  resource_permissions: Array<ResourcePermissionResponse>;
};
