// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserProfileDataResponse = {
  first_name: string | null;
  last_name: string | null;
  avatar_url: string | null;
};
