// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionResponse } from "./PermissionResponse";
import type { ResourcePermissionResponse } from "./ResourcePermissionResponse";

export type UserPermissionResponse = {
  rbac_permissions: Array<PermissionResponse>;
  acl_permissions: Array<ResourcePermissionResponse>;
};
