import fs from 'fs'
import matter from 'gray-matter'
import path from 'path'

const docsDir = path.join(process.cwd(), 'src/lib/docs')
const outputFile = path.join(process.cwd(), 'src/lib/utils/search-index.ts')

interface SearchEntry {
  slug: string
  title: string
  description?: string
  content: string
  order: number
}

const entries: SearchEntry[] = []

const files = fs.readdirSync(docsDir)

for (const file of files) {
  if (!file.endsWith('.md')) continue

  const filePath = path.join(docsDir, file)
  const content = fs.readFileSync(filePath, 'utf-8')
  const { data, content: body } = matter(content)

  entries.push({
    slug: file.replace('.md', ''),
    title: data.title,
    description: data.description,
    content: body,
    order: data.order || 99,
  })
}

entries.sort((a, b) => a.order - b.order)

const output = `// Auto-generated by scripts/build-search-index.ts
export const searchIndex = ${JSON.stringify(entries, null, 2)} as const;
export type SearchEntry = typeof searchIndex[number];
`

fs.writeFileSync(outputFile, output)
console.log(`Generated search index with ${entries.length} documents`)
