import dotenv from 'dotenv'
import fs from 'fs'
import matter from 'gray-matter'
import { MeiliSearch } from 'meilisearch'
import path from 'path'

dotenv.config({ path: path.join(process.cwd(), '../../.env') })

const docsDir = path.join(process.cwd(), 'src/lib/docs')
const outputFile = path.join(process.cwd(), 'src/lib/utils/search-index.ts')

interface SearchEntry {
  id: string
  slug: string
  title: string
  description?: string
  content: string
  section: string
  order: number
}

const entries: SearchEntry[] = []

const files = fs.readdirSync(docsDir)

for (const file of files) {
  if (!file.endsWith('.md')) continue

  const filePath = path.join(docsDir, file)
  const content = fs.readFileSync(filePath, 'utf-8')
  const { data, content: body } = matter(content)

  entries.push({
    id: file.replace('.md', ''),
    slug: file.replace('.md', ''),
    title: data.title,
    description: data.description,
    content: body,
    section: data.section || 'General',
    order: data.order || 99,
  })
}

entries.sort((a, b) => a.order - b.order)

const output = `// Auto-generated by scripts/build-search-index.ts
export const searchIndex = ${JSON.stringify(entries, null, 2)} as const;
export type SearchEntry = typeof searchIndex[number];
`

fs.writeFileSync(outputFile, output)
console.log(`Generated search index with ${entries.length} documents`)

// Index into MeiliSearch
const meiliHost = process.env.MEILI_HOST || 'http://localhost:7700'
const meiliKey = process.env.MEILI_MASTER_KEY || 'aSampleMasterKey'

const client = new MeiliSearch({
  host: meiliHost,
  apiKey: meiliKey,
})

async function indexDocs() {
  try {
    const index = client.index('docs')
    await index.addDocuments(entries)
    console.log(`Indexed ${entries.length} documents into MeiliSearch`)

    // Configure index settings
    await index.updateSettings({
      searchableAttributes: ['title', 'content', 'description'],
      displayedAttributes: ['id', 'slug', 'title', 'description', 'section'],
      rankingRules: [
        'words',
        'typo',
        'proximity',
        'attribute',
        'sort',
        'exactness',
      ],
      typoTolerance: {
        enabled: true,
      },
      pagination: {
        maxTotalHits: 100,
      },
    })
    console.log('Updated MeiliSearch index settings')
  } catch (error) {
    console.error('Error indexing into MeiliSearch:', error)
  }
}

indexDocs()
