use std::path::Path;
use ts_rs::TS;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("🚀 Exporting TypeScript definitions...");

    // Import types using module paths from backend lib
    use backend::entries::dtos::payload::auth::{
        LoginRequest, RefreshTokenRequest, RegisterUserRequest,
    };
    use backend::entries::dtos::response::auth::{
        AuthResponse, MeResponse, PermissionResponse, RoleResponse, TokenResponse, UserResponse,
    };
    use backend::entries::dtos::response::common::{
        ErrorResponse, PaginationInfo, SuccessResponse,
    };
    use backend::entries::entitiy_enums::{
        action_types::ActionTypeEnum, resource_types::ResourceTypeEnum, user_types::UserTypeEnums,
    };

    // Set output directory for monorepo
    let output_dir = Path::new("../../packages/api-client/src/generated-types");
    std::fs::create_dir_all(output_dir)?;

    println!("📁 Output directory: {}", output_dir.display());

    // Export all types using ts-rs
    println!("📦 Exporting Auth Payload DTOs...");
    LoginRequest::export()?;
    RegisterUserRequest::export()?;
    RefreshTokenRequest::export()?;

    println!("📦 Exporting Auth Response DTOs...");
    AuthResponse::export()?;
    TokenResponse::export()?;
    UserResponse::export()?;
    MeResponse::export()?;
    RoleResponse::export()?;
    PermissionResponse::export()?;

    println!("📦 Exporting Common DTOs...");
    PaginationInfo::export()?;
    SuccessResponse::export()?;
    ErrorResponse::export()?;

    println!("📦 Exporting Enum Types...");
    UserTypeEnums::export()?;
    ActionTypeEnum::export()?;
    ResourceTypeEnum::export()?;

    // Generate custom UUID type
    let uuid_content = r#"// Generated by ts-rs
export type Uuid = string;
"#;
    std::fs::write(output_dir.join("uuid.ts"), uuid_content)?;

    // Generate main index.ts that exports everything
    let index_content = r#"// Generated by ts-rs
export type { Uuid } from './uuid';
export type { Date } from './date';

// Auth Payload Types
export type { LoginRequest, RegisterUserRequest, RefreshTokenRequest } from './payload/auth';

// Auth Response Types
export type { AuthResponse, TokenResponse, UserResponse, MeResponse, RoleResponse, PermissionResponse } from './response/auth';

// Common Response Types
export type { PaginationInfo, SuccessResponse, ErrorResponse } from './response/common';

// Enum Types
export type { UserTypeEnums, ActionTypeEnum, ResourceTypeEnum } from './enums/types';
"#;
    std::fs::write(output_dir.join("index.ts"), index_content)?;

    println!("✅ TypeScript definitions exported successfully!");
    println!("📂 Generated files in: {}", output_dir.display());

    // List generated files
    if let Ok(entries) = std::fs::read_dir(output_dir) {
        println!("📋 Generated files:");
        for entry in entries.flatten() {
            println!("   📄 {}", entry.file_name().to_string_lossy());
        }
    }

    Ok(())
}
