/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRoutesRouteImport } from './routes/_private-routes'
import { Route as PrivateRoutesIndexRouteImport } from './routes/_private-routes/index'
import { Route as AuthAuthLayoutRouteImport } from './routes/auth/_auth-layout'
import { Route as AuthAuthLayoutIndexRouteImport } from './routes/auth/_auth-layout/index'
import { Route as PrivateRoutesSettingsIndexRouteImport } from './routes/_private-routes/settings/index'
import { Route as PrivateRoutesQuizzesIndexRouteImport } from './routes/_private-routes/quizzes/index'
import { Route as PrivateRoutesLiveClassesIndexRouteImport } from './routes/_private-routes/live-classes/index'
import { Route as PrivateRoutesDashboardIndexRouteImport } from './routes/_private-routes/dashboard/index'
import { Route as PrivateRoutesCommunityIndexRouteImport } from './routes/_private-routes/community/index'
import { Route as PrivateRoutesAnalyticsIndexRouteImport } from './routes/_private-routes/analytics/index'
import { Route as AuthAuthLayoutLoginRouteImport } from './routes/auth/_auth-layout/login'
import { Route as AuthAuthLayoutForgotPasswordRouteImport } from './routes/auth/_auth-layout/forgot-password'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PrivateRoutesContentContentLayoutRouteImport } from './routes/_private-routes/content/_content-layout'
import { Route as PrivateRoutesContentContentLayoutIndexRouteImport } from './routes/_private-routes/content/_content-layout/index'
import { Route as PrivateRoutesContentContentLayoutTopicIdRouteImport } from './routes/_private-routes/content/_content-layout/topic/$id'

const PrivateRoutesRoute = PrivateRoutesRouteImport.update({
  id: '/_private-routes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoutesIndexRoute = PrivateRoutesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoutesRoute,
} as any)
const AuthAuthLayoutRoute = AuthAuthLayoutRouteImport.update({
  id: '/auth/_auth-layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthLayoutIndexRoute = AuthAuthLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)
const PrivateRoutesSettingsIndexRoute =
  PrivateRoutesSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => PrivateRoutesRoute,
  } as any)
const PrivateRoutesQuizzesIndexRoute =
  PrivateRoutesQuizzesIndexRouteImport.update({
    id: '/quizzes/',
    path: '/quizzes/',
    getParentRoute: () => PrivateRoutesRoute,
  } as any)
const PrivateRoutesLiveClassesIndexRoute =
  PrivateRoutesLiveClassesIndexRouteImport.update({
    id: '/live-classes/',
    path: '/live-classes/',
    getParentRoute: () => PrivateRoutesRoute,
  } as any)
const PrivateRoutesDashboardIndexRoute =
  PrivateRoutesDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => PrivateRoutesRoute,
  } as any)
const PrivateRoutesCommunityIndexRoute =
  PrivateRoutesCommunityIndexRouteImport.update({
    id: '/community/',
    path: '/community/',
    getParentRoute: () => PrivateRoutesRoute,
  } as any)
const PrivateRoutesAnalyticsIndexRoute =
  PrivateRoutesAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => PrivateRoutesRoute,
  } as any)
const AuthAuthLayoutLoginRoute = AuthAuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)
const AuthAuthLayoutForgotPasswordRoute =
  AuthAuthLayoutForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => AuthAuthLayoutRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoutesContentContentLayoutRoute =
  PrivateRoutesContentContentLayoutRouteImport.update({
    id: '/content/_content-layout',
    path: '/content',
    getParentRoute: () => PrivateRoutesRoute,
  } as any)
const PrivateRoutesContentContentLayoutIndexRoute =
  PrivateRoutesContentContentLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateRoutesContentContentLayoutRoute,
  } as any)
const PrivateRoutesContentContentLayoutTopicIdRoute =
  PrivateRoutesContentContentLayoutTopicIdRouteImport.update({
    id: '/topic/$id',
    path: '/topic/$id',
    getParentRoute: () => PrivateRoutesContentContentLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivateRoutesIndexRoute
  '/auth': typeof AuthAuthLayoutRouteWithChildren
  '/content': typeof PrivateRoutesContentContentLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/forgot-password': typeof AuthAuthLayoutForgotPasswordRoute
  '/auth/login': typeof AuthAuthLayoutLoginRoute
  '/analytics/': typeof PrivateRoutesAnalyticsIndexRoute
  '/community/': typeof PrivateRoutesCommunityIndexRoute
  '/dashboard/': typeof PrivateRoutesDashboardIndexRoute
  '/live-classes/': typeof PrivateRoutesLiveClassesIndexRoute
  '/quizzes/': typeof PrivateRoutesQuizzesIndexRoute
  '/settings/': typeof PrivateRoutesSettingsIndexRoute
  '/auth/': typeof AuthAuthLayoutIndexRoute
  '/content/': typeof PrivateRoutesContentContentLayoutIndexRoute
  '/content/topic/$id': typeof PrivateRoutesContentContentLayoutTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateRoutesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/forgot-password': typeof AuthAuthLayoutForgotPasswordRoute
  '/auth/login': typeof AuthAuthLayoutLoginRoute
  '/analytics': typeof PrivateRoutesAnalyticsIndexRoute
  '/community': typeof PrivateRoutesCommunityIndexRoute
  '/dashboard': typeof PrivateRoutesDashboardIndexRoute
  '/live-classes': typeof PrivateRoutesLiveClassesIndexRoute
  '/quizzes': typeof PrivateRoutesQuizzesIndexRoute
  '/settings': typeof PrivateRoutesSettingsIndexRoute
  '/auth': typeof AuthAuthLayoutIndexRoute
  '/content': typeof PrivateRoutesContentContentLayoutIndexRoute
  '/content/topic/$id': typeof PrivateRoutesContentContentLayoutTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private-routes': typeof PrivateRoutesRouteWithChildren
  '/auth/_auth-layout': typeof AuthAuthLayoutRouteWithChildren
  '/_private-routes/': typeof PrivateRoutesIndexRoute
  '/_private-routes/content/_content-layout': typeof PrivateRoutesContentContentLayoutRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/_auth-layout/forgot-password': typeof AuthAuthLayoutForgotPasswordRoute
  '/auth/_auth-layout/login': typeof AuthAuthLayoutLoginRoute
  '/_private-routes/analytics/': typeof PrivateRoutesAnalyticsIndexRoute
  '/_private-routes/community/': typeof PrivateRoutesCommunityIndexRoute
  '/_private-routes/dashboard/': typeof PrivateRoutesDashboardIndexRoute
  '/_private-routes/live-classes/': typeof PrivateRoutesLiveClassesIndexRoute
  '/_private-routes/quizzes/': typeof PrivateRoutesQuizzesIndexRoute
  '/_private-routes/settings/': typeof PrivateRoutesSettingsIndexRoute
  '/auth/_auth-layout/': typeof AuthAuthLayoutIndexRoute
  '/_private-routes/content/_content-layout/': typeof PrivateRoutesContentContentLayoutIndexRoute
  '/_private-routes/content/_content-layout/topic/$id': typeof PrivateRoutesContentContentLayoutTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/content'
    | '/api/auth/$'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/analytics/'
    | '/community/'
    | '/dashboard/'
    | '/live-classes/'
    | '/quizzes/'
    | '/settings/'
    | '/auth/'
    | '/content/'
    | '/content/topic/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/analytics'
    | '/community'
    | '/dashboard'
    | '/live-classes'
    | '/quizzes'
    | '/settings'
    | '/auth'
    | '/content'
    | '/content/topic/$id'
  id:
    | '__root__'
    | '/_private-routes'
    | '/auth/_auth-layout'
    | '/_private-routes/'
    | '/_private-routes/content/_content-layout'
    | '/api/auth/$'
    | '/auth/_auth-layout/forgot-password'
    | '/auth/_auth-layout/login'
    | '/_private-routes/analytics/'
    | '/_private-routes/community/'
    | '/_private-routes/dashboard/'
    | '/_private-routes/live-classes/'
    | '/_private-routes/quizzes/'
    | '/_private-routes/settings/'
    | '/auth/_auth-layout/'
    | '/_private-routes/content/_content-layout/'
    | '/_private-routes/content/_content-layout/topic/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRoutesRoute: typeof PrivateRoutesRouteWithChildren
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private-routes': {
      id: '/_private-routes'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private-routes/': {
      id: '/_private-routes/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateRoutesIndexRouteImport
      parentRoute: typeof PrivateRoutesRoute
    }
    '/auth/_auth-layout': {
      id: '/auth/_auth-layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_auth-layout/': {
      id: '/auth/_auth-layout/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthAuthLayoutIndexRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/_private-routes/settings/': {
      id: '/_private-routes/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof PrivateRoutesSettingsIndexRouteImport
      parentRoute: typeof PrivateRoutesRoute
    }
    '/_private-routes/quizzes/': {
      id: '/_private-routes/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof PrivateRoutesQuizzesIndexRouteImport
      parentRoute: typeof PrivateRoutesRoute
    }
    '/_private-routes/live-classes/': {
      id: '/_private-routes/live-classes/'
      path: '/live-classes'
      fullPath: '/live-classes/'
      preLoaderRoute: typeof PrivateRoutesLiveClassesIndexRouteImport
      parentRoute: typeof PrivateRoutesRoute
    }
    '/_private-routes/dashboard/': {
      id: '/_private-routes/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof PrivateRoutesDashboardIndexRouteImport
      parentRoute: typeof PrivateRoutesRoute
    }
    '/_private-routes/community/': {
      id: '/_private-routes/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof PrivateRoutesCommunityIndexRouteImport
      parentRoute: typeof PrivateRoutesRoute
    }
    '/_private-routes/analytics/': {
      id: '/_private-routes/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof PrivateRoutesAnalyticsIndexRouteImport
      parentRoute: typeof PrivateRoutesRoute
    }
    '/auth/_auth-layout/login': {
      id: '/auth/_auth-layout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLayoutLoginRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/auth/_auth-layout/forgot-password': {
      id: '/auth/_auth-layout/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthAuthLayoutForgotPasswordRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private-routes/content/_content-layout': {
      id: '/_private-routes/content/_content-layout'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof PrivateRoutesContentContentLayoutRouteImport
      parentRoute: typeof PrivateRoutesRoute
    }
    '/_private-routes/content/_content-layout/': {
      id: '/_private-routes/content/_content-layout/'
      path: '/'
      fullPath: '/content/'
      preLoaderRoute: typeof PrivateRoutesContentContentLayoutIndexRouteImport
      parentRoute: typeof PrivateRoutesContentContentLayoutRoute
    }
    '/_private-routes/content/_content-layout/topic/$id': {
      id: '/_private-routes/content/_content-layout/topic/$id'
      path: '/topic/$id'
      fullPath: '/content/topic/$id'
      preLoaderRoute: typeof PrivateRoutesContentContentLayoutTopicIdRouteImport
      parentRoute: typeof PrivateRoutesContentContentLayoutRoute
    }
  }
}

interface PrivateRoutesContentContentLayoutRouteChildren {
  PrivateRoutesContentContentLayoutIndexRoute: typeof PrivateRoutesContentContentLayoutIndexRoute
  PrivateRoutesContentContentLayoutTopicIdRoute: typeof PrivateRoutesContentContentLayoutTopicIdRoute
}

const PrivateRoutesContentContentLayoutRouteChildren: PrivateRoutesContentContentLayoutRouteChildren =
  {
    PrivateRoutesContentContentLayoutIndexRoute:
      PrivateRoutesContentContentLayoutIndexRoute,
    PrivateRoutesContentContentLayoutTopicIdRoute:
      PrivateRoutesContentContentLayoutTopicIdRoute,
  }

const PrivateRoutesContentContentLayoutRouteWithChildren =
  PrivateRoutesContentContentLayoutRoute._addFileChildren(
    PrivateRoutesContentContentLayoutRouteChildren,
  )

interface PrivateRoutesRouteChildren {
  PrivateRoutesIndexRoute: typeof PrivateRoutesIndexRoute
  PrivateRoutesContentContentLayoutRoute: typeof PrivateRoutesContentContentLayoutRouteWithChildren
  PrivateRoutesAnalyticsIndexRoute: typeof PrivateRoutesAnalyticsIndexRoute
  PrivateRoutesCommunityIndexRoute: typeof PrivateRoutesCommunityIndexRoute
  PrivateRoutesDashboardIndexRoute: typeof PrivateRoutesDashboardIndexRoute
  PrivateRoutesLiveClassesIndexRoute: typeof PrivateRoutesLiveClassesIndexRoute
  PrivateRoutesQuizzesIndexRoute: typeof PrivateRoutesQuizzesIndexRoute
  PrivateRoutesSettingsIndexRoute: typeof PrivateRoutesSettingsIndexRoute
}

const PrivateRoutesRouteChildren: PrivateRoutesRouteChildren = {
  PrivateRoutesIndexRoute: PrivateRoutesIndexRoute,
  PrivateRoutesContentContentLayoutRoute:
    PrivateRoutesContentContentLayoutRouteWithChildren,
  PrivateRoutesAnalyticsIndexRoute: PrivateRoutesAnalyticsIndexRoute,
  PrivateRoutesCommunityIndexRoute: PrivateRoutesCommunityIndexRoute,
  PrivateRoutesDashboardIndexRoute: PrivateRoutesDashboardIndexRoute,
  PrivateRoutesLiveClassesIndexRoute: PrivateRoutesLiveClassesIndexRoute,
  PrivateRoutesQuizzesIndexRoute: PrivateRoutesQuizzesIndexRoute,
  PrivateRoutesSettingsIndexRoute: PrivateRoutesSettingsIndexRoute,
}

const PrivateRoutesRouteWithChildren = PrivateRoutesRoute._addFileChildren(
  PrivateRoutesRouteChildren,
)

interface AuthAuthLayoutRouteChildren {
  AuthAuthLayoutForgotPasswordRoute: typeof AuthAuthLayoutForgotPasswordRoute
  AuthAuthLayoutLoginRoute: typeof AuthAuthLayoutLoginRoute
  AuthAuthLayoutIndexRoute: typeof AuthAuthLayoutIndexRoute
}

const AuthAuthLayoutRouteChildren: AuthAuthLayoutRouteChildren = {
  AuthAuthLayoutForgotPasswordRoute: AuthAuthLayoutForgotPasswordRoute,
  AuthAuthLayoutLoginRoute: AuthAuthLayoutLoginRoute,
  AuthAuthLayoutIndexRoute: AuthAuthLayoutIndexRoute,
}

const AuthAuthLayoutRouteWithChildren = AuthAuthLayoutRoute._addFileChildren(
  AuthAuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRoutesRoute: PrivateRoutesRouteWithChildren,
  AuthAuthLayoutRoute: AuthAuthLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
