use sea_orm_migration::{
    DbErr, MigrationTrait, SchemaManager, async_trait,
    prelude::{ColumnDef, ForeignKey, ForeignKeyAction, Index, Table},
    sea_orm::DeriveMigrationName,
};

use crate::identifiers::{
    content_table::{ContentTopicTableIdentifier, ContentVideoTableIdentifier},
    learning_table::{
        LearningNotesTableIdentifier, LearningProgressTableIdentifier,
        LearningRecallAnswerTableIdentifier, LearningRecallSessionTableIdentifier,
    },
    user_table::UserTableIdentifiers,
};

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(LearningNotesTableIdentifier::Table)
                    .col(
                        ColumnDef::new(LearningNotesTableIdentifier::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(LearningNotesTableIdentifier::TopicId)
                            .uuid()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_learning_notes_topic")
                            .from(
                                LearningNotesTableIdentifier::Table,
                                LearningNotesTableIdentifier::TopicId,
                            )
                            .to(
                                ContentTopicTableIdentifier::Table,
                                ContentTopicTableIdentifier::Id,
                            )
                            .on_delete(ForeignKeyAction::Cascade)
                            .on_update(ForeignKeyAction::Cascade),
                    )
                    .col(
                        ColumnDef::new(LearningNotesTableIdentifier::OwnerType)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(LearningNotesTableIdentifier::OwnerId).uuid())
                    .col(ColumnDef::new(LearningNotesTableIdentifier::VideoId).uuid())
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_learning_notes_video")
                            .from(
                                LearningNotesTableIdentifier::Table,
                                LearningNotesTableIdentifier::VideoId,
                            )
                            .to(
                                ContentVideoTableIdentifier::Table,
                                ContentVideoTableIdentifier::Id,
                            )
                            .on_delete(ForeignKeyAction::Cascade)
                            .on_update(ForeignKeyAction::Cascade),
                    )
                    .col(ColumnDef::new(LearningNotesTableIdentifier::VideoTimestamp).integer())
                    .col(
                        ColumnDef::new(LearningNotesTableIdentifier::ContentType)
                            .custom("notes_content_type")
                            .not_null(),
                    )
                    .col(ColumnDef::new(LearningNotesTableIdentifier::Content).text())
                    .col(ColumnDef::new(LearningNotesTableIdentifier::ExternalUrl).text())
                    .col(ColumnDef::new(LearningNotesTableIdentifier::ExternalType).text())
                    .col(
                        ColumnDef::new(LearningNotesTableIdentifier::IsPublic)
                            .boolean()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LearningNotesTableIdentifier::TrustLevel)
                            .custom("trust_level")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LearningNotesTableIdentifier::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LearningNotesTableIdentifier::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LearningNotesTableIdentifier::DeletedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(LearningProgressTableIdentifier::Table)
                    .col(
                        ColumnDef::new(LearningProgressTableIdentifier::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(LearningProgressTableIdentifier::TopicId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LearningProgressTableIdentifier::UserId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LearningProgressTableIdentifier::ProgressPercent)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LearningProgressTableIdentifier::LastAccessedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_learning_progress_user")
                            .from(
                                LearningProgressTableIdentifier::Table,
                                LearningProgressTableIdentifier::UserId,
                            )
                            .to(UserTableIdentifiers::Table, UserTableIdentifiers::Id)
                            .on_delete(ForeignKeyAction::Cascade)
                            .on_update(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_learning_progress_topic")
                            .from(
                                LearningProgressTableIdentifier::Table,
                                LearningProgressTableIdentifier::TopicId,
                            )
                            .to(
                                ContentTopicTableIdentifier::Table,
                                ContentTopicTableIdentifier::Id,
                            )
                            .on_delete(ForeignKeyAction::Cascade)
                            .on_update(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(LearningRecallSessionTableIdentifier::Table)
                    .col(
                        ColumnDef::new(LearningRecallSessionTableIdentifier::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(LearningRecallSessionTableIdentifier::UserId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LearningRecallSessionTableIdentifier::TopicId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LearningRecallSessionTableIdentifier::Status)
                            .custom("learning_recall_session_status")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LearningRecallSessionTableIdentifier::StartedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LearningRecallSessionTableIdentifier::CompletedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_learning_recall_session_user")
                            .from(
                                LearningRecallSessionTableIdentifier::Table,
                                LearningRecallSessionTableIdentifier::UserId,
                            )
                            .to(UserTableIdentifiers::Table, UserTableIdentifiers::Id)
                            .on_delete(ForeignKeyAction::Cascade)
                            .on_update(ForeignKeyAction::Cascade),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_learning_recall_session_topic")
                            .from(
                                LearningRecallSessionTableIdentifier::Table,
                                LearningRecallSessionTableIdentifier::TopicId,
                            )
                            .to(
                                ContentTopicTableIdentifier::Table,
                                ContentTopicTableIdentifier::Id,
                            )
                            .on_delete(ForeignKeyAction::Cascade)
                            .on_update(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(LearningRecallAnswerTableIdentifier::Table)
                    .col(
                        ColumnDef::new(LearningRecallAnswerTableIdentifier::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(LearningRecallAnswerTableIdentifier::SessionId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LearningRecallAnswerTableIdentifier::QuestionType)
                            .custom("learning_recall_question_type")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LearningRecallAnswerTableIdentifier::Question)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LearningRecallAnswerTableIdentifier::Answer)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(LearningRecallAnswerTableIdentifier::IsCorrect)
                            .boolean()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_learning_recall_answer_session")
                            .from(
                                LearningRecallAnswerTableIdentifier::Table,
                                LearningRecallAnswerTableIdentifier::SessionId,
                            )
                            .to(
                                LearningRecallSessionTableIdentifier::Table,
                                LearningRecallSessionTableIdentifier::Id,
                            )
                            .on_delete(ForeignKeyAction::Cascade)
                            .on_update(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;
        // Create indexes
        manager
            .create_index(
                Index::create()
                    .name("idx_learning_notes_topic")
                    .table(LearningNotesTableIdentifier::Table)
                    .col(LearningNotesTableIdentifier::TopicId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_learning_notes_owner")
                    .table(LearningNotesTableIdentifier::Table)
                    .col(LearningNotesTableIdentifier::OwnerType)
                    .col(LearningNotesTableIdentifier::OwnerId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_learning_notes_video")
                    .table(LearningNotesTableIdentifier::Table)
                    .col(LearningNotesTableIdentifier::VideoId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_learning_notes_public")
                    .table(LearningNotesTableIdentifier::Table)
                    .col(LearningNotesTableIdentifier::IsPublic)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("uniq_learning_progress_user_topic")
                    .table(LearningProgressTableIdentifier::Table)
                    .col(LearningProgressTableIdentifier::UserId)
                    .col(LearningProgressTableIdentifier::TopicId)
                    .unique()
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_learning_progress_user")
                    .table(LearningProgressTableIdentifier::Table)
                    .col(LearningProgressTableIdentifier::UserId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_learning_recall_session_user")
                    .table(LearningRecallSessionTableIdentifier::Table)
                    .col(LearningRecallSessionTableIdentifier::UserId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .name("idx_learning_recall_session_topic")
                    .table(LearningRecallSessionTableIdentifier::Table)
                    .col(LearningRecallSessionTableIdentifier::TopicId)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // Drop indexes
        manager
            .drop_index(Index::drop().name("idx_learning_notes_topic").to_owned())
            .await?;
        manager
            .drop_index(Index::drop().name("idx_learning_notes_owner").to_owned())
            .await?;
        manager
            .drop_index(Index::drop().name("idx_learning_notes_video").to_owned())
            .await?;
        manager
            .drop_index(Index::drop().name("idx_learning_notes_public").to_owned())
            .await?;
        manager
            .drop_index(
                Index::drop()
                    .name("uniq_learning_progress_user_topic")
                    .to_owned(),
            )
            .await?;
        manager
            .drop_index(Index::drop().name("idx_learning_progress_user").to_owned())
            .await?;
        manager
            .drop_index(
                Index::drop()
                    .name("idx_learning_recall_session_user")
                    .to_owned(),
            )
            .await?;
        manager
            .drop_index(
                Index::drop()
                    .name("idx_learning_recall_session_topic")
                    .to_owned(),
            )
            .await?;

        // Drop tables
        manager
            .drop_table(
                Table::drop()
                    .table(LearningNotesTableIdentifier::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(LearningProgressTableIdentifier::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(LearningRecallAnswerTableIdentifier::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(LearningRecallSessionTableIdentifier::Table)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }
}
